const data = [
  {
    _id: "679bc4e41aa5fe6a513076a4",
    categories: "Wall-Shelves",
    rooms: "Kitchen",
    productName: "AltOrganisers Mug Loft Wooden Coffee & Tea Cup Organizer",
    sku: "ALT-COFF-01-BRN",
    handlingtime: "3",
    mrp: "5999",
    sellingprice: "5999",
    Material: "Acacia Wood",
    Warranty: "12",
    theme: "",
    dimensions: ["57*3*50.5"],
    weight: "7",
    keyfeatures: [""],
    descriptions: [
      "Transform your space with our elegant wall shelf! Measuring 57*3*50.5 inches with a 9 mm thick shelf, it can hold up to 10 kg, making it perfect for displaying decor or storing important items. The minimalist design fits into any room and offers both style and functionality in a compact unit.",
    ],
    variants: [
      {
        finish: "Honey Oak",
        images: [
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738261725/Altorganizer/products/sfnaysdwfhvufqlt1b7p.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738261726/Altorganizer/products/y85bfyjwqmuwmoayzcqt.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738261727/Altorganizer/products/ssmaarybdcbpaewfaxlq.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738261727/Altorganizer/products/y4hqvyehhcsouymranvt.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738261728/Altorganizer/products/cqn58hho4a7ibys1lvlc.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738261729/Altorganizer/products/nijqpp09g1zgemyjkml6.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738261729/Altorganizer/products/dybkao7eos2quei08ewh.png",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738261730/Altorganizer/products/h9qn0nv883j7avkyupyw.png",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738261731/Altorganizer/products/v4wzigosxhhbnwycxbdv.png",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738261725/Altorganizer/products/hiuo2gqprq0mhhwz0q5y.jpg",
        ],
      },
    ],
    seotitle:
      "Wooden Coffee Cup Rack, Storage Display Grid Coffee Cup, Tea Cup Holder Solid Wood Water Cup Lattice Rack",
    seodescription:
      "Transform your space with our elegant wall shelf! Measuring 57*3*50.5 inches with a 9 mm thick shelf, it can hold up to 10 kg, making it perfect for displaying decor or storing important items. The minimalist design fits into any room and offers both style and functionality in a compact unit.",
    seokeywords: "",
    available: true,
    lastupdated: 1738262637541,
  },
  {
    _id: "679bccf7a501d3888eb82235",
    categories: "Wall-Shelves",
    rooms: "Kitchen",
    productName: "AltOrganisers Monaco Wooden Coffee & Tea Cup Organizer",
    sku: "ALT-COFF-02-BRN",
    handlingtime: "3",
    mrp: "4999",
    sellingprice: "4999",
    Material: "Acacia Wood",
    Warranty: "12",
    theme: "",
    dimensions: ["46D x 11.5W x 61H Centimeters "],
    weight: "4000",
    keyfeatures: [
      "12-cubby design: Features 12 compartments for organizing and displaying mugs, crystals, trinkets, and more. Premium Acacia wood: Crafted from high-quality Acacia wood with a rich grain finish for a timeless look. Versatile storage: Ideal for use in kitchens, living rooms, bedrooms, or offices to save space and stay organized. Wall-mounted solution: Easy to mount with included hardware, creating a stylish floating shelf effect. Elegant and functional: Combines practical storage with decorative appeal, enhancing any room's decor. Compact design: Perfect for small spaces where floor space is limited, offering a space-saving solution. Modern aesthetic: Clean, geometric lines with natural wood tones that complement various interior styles.\"",
      "",
    ],
    descriptions: [
      "Transform your space with our elegant wall shelf! With a 9 mm thick shelf, it can hold up to 10 kg, making it perfect for displaying decor or storing important items. The minimalist design fits into any room and offers both style and functionality in a compact unit.",
    ],
    variants: [
      {
        finish: "Honey Oak",
        images: [
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738263797/Altorganizer/products/frrpi9rfldraugzpuawb.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738263798/Altorganizer/products/mcmu5lbpjgoxbrsfwpey.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738263798/Altorganizer/products/dhufvl5fzssg7yymppgo.jpg",
        ],
      },
    ],
    seotitle:
      "Rectangular Wall Rack - 12-Cubby Acacia Wood Shelf with Rich Grain Finish, Perfect for Displaying Mugs, Crystals, Trinkets, and More, Wall-Mounted Storage Solution for Any Room",
    seodescription: "",
    seokeywords: "",
    available: true,
    lastupdated: 1738263799290,
  },
  {
    _id: "679bda5450599c26b1728c46",
    categories: "Photo-Frames",
    rooms: "Living-Room",
    productName: "AltOrganisers Montessori Bookshelf for Toddlers Book Storage",
    sku: "ALT-BOOKORG-02-NATURAL",
    handlingtime: "3",
    mrp: "5999",
    sellingprice: "5999",
    Material: "Acacia Wood",
    Warranty: "12",
    theme: "",
    dimensions: ["26.9D x 41.9W x 41.9H centimeters"],
    weight: "6000",
    keyfeatures: [
      "High Quality Material: Made from high-quality wood, this book display shelf is sturdy and built to withstand the active use of children. The practical construction ensures long-lasting use,designed to withstand the weight of multiple books on each tier ",
      "Child-Friendly Design: Height appropriate for easy access by children.Encourages them to select and return books independently.Sturdy back support adds extra stability to the bookshelf.Prevents wobbling and ensures safety during use",
      "Front-Facing Design: The front-facing shelves make it easy for kids to see and access their favorite books. This encourages independent reading and creates an engaging and visually appealing display ",
      "Back Chalkboard: The back panel of the shelf doubles as a chalkboard. This adds an interactive element, allowing kids to express their creativity by drawing, writing, or labeling the books. It also serves as a handy space for educational notes or reminders ",
      "5-Tier Book Display: The shelf features five tiers, providing ample space for organizing and showcasing a variety of books. Each tier is designed to accommodate different book sizes, making it versatile for various reading materials",
    ],
    descriptions: [""],
    variants: [
      {
        finish: "Honey Oak",
        images: [
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738267215/Altorganizer/products/kv5h2au3zvrwnw9xcad0.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738267216/Altorganizer/products/vnlkdkoddbdevckfcukg.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738267217/Altorganizer/products/l1chvnkb4l62lnpx0d5l.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738267218/Altorganizer/products/luqhknpjtbniflp8mhan.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738267219/Altorganizer/products/qdf2f5jbyixkzq6w2rxb.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738267220/Altorganizer/products/cxv5wz6c2uap2wknlo0u.jpg",
        ],
      },
    ],
    seotitle:
      "Montessori Bookshelf for Toddler 1-5 Years, Kids Wooden 5-Tier Front Facing Book Display Shelf with Chalkboard for Bedroom,Playroom,Classroom,Book Rack Organizer, Natural",
    seodescription: "",
    seokeywords: "",
    available: true,
    lastupdated: 1738267220500,
  },
  {
    _id: "679c53f50d060dee6150cccf",
    categories: "Pantry-Organizers",
    rooms: "Living-Room",
    productName: "test",
    sku: "testsku",
    handlingtime: "7-8 days",
    mrp: "1000",
    sellingprice: "998",
    Material: "Acacia Wood",
    Warranty: "8",
    theme: "this is a test theme",
    dimensions: ["this is a dimensin"],
    weight: "90",
    keyfeatures: ["sdasdsa", "aasads"],
    descriptions: ["sdasdsa", "asdasdasdasd"],
    variants: [
      {
        finish: "Honey Oak",
        images: [
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738298354/Altorganizer/products/ppllfvy0n3e52a0sezh0.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738298356/Altorganizer/products/dsoe8w6pmulwir6x8u8o.jpg",
        ],
      },
    ],
    seotitle: "test title",
    seodescription: "test desc",
    seokeywords: "test keywords",
    available: false,
    lastupdated: 1738299380797,
  },
  {
    _id: "679cca81ed7d5876ba054305",
    categories: "Wall-Shelves",
    rooms: "Kitchen",
    productName: "AltOrganisers 3 Tier Spice Rack Eco Friendly Organizer",
    sku: "ALT-KITN-ORG-01-NAT",
    handlingtime: "3",
    mrp: "1999",
    sellingprice: "1999",
    Material: "Acacia Wood",
    Warranty: "12",
    theme: "",
    dimensions: ["20D x 10W x 10H cm"],
    weight: "7",
    keyfeatures: [
      "Made of natural wood with a water resistant finish, this three tier organizer provides sturdy storage and display for your spices and condiments.",
      "Featuring three adjustable shelves, this rack organizes your spices neatly while saving valuable cabinet and counter space.",
      "Open shelf design allows full visibility of all your spices while the tiered structure makes even bottles at the back easy to access.",
      "Lightweight and portable, this organizer sets up easily on counters or inside cabinets to categorize your seasonings wherever needed.",
      "Smooth, finish makes wiping down a breeze to keep this organizer looking fresh. Wire shelves are removable for thorough cleaning when needed.",
    ],
    descriptions: [""],
    variants: [
      {
        finish: "Honey Oak",
        images: [
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738328701/Altorganizer/products/gjwmuvd76xctnaw09ti2.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738328701/Altorganizer/products/j9p74adsxdfuh9v4rolm.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738328702/Altorganizer/products/olr9lo1gtf702lv7do5c.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738328702/Altorganizer/products/cbkhlzkiyzpj9sq0ist3.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738328703/Altorganizer/products/olfeelxxw4xemlg25ylv.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738328704/Altorganizer/products/pcxztsc9v05uyinfoixc.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738328704/Altorganizer/products/cxud3ipfxe6abcld8va7.jpg",
        ],
      },
    ],
    seotitle:
      "3 Tier Bamboo Spice Rack Free Standing, Eco Friendly Space Saving Spice Organizer, Metal Seasoning Bottle Organizer for Kitchen, Countertop, Cupboard, Pantry,Cabinet Drawers (Horizontal)",
    seodescription: "",
    seokeywords: "",
    available: true,
    lastupdated: 1738328763978,
  },
  {
    _id: "67a1f588f947d97235b59bc7",
    categories: "Drawer-Organizers",
    rooms: "Kitchen",
    productName: "AltOrganisers Silverware for Kitchen Drawer Organizer",
    sku: "ALT-KITN-ORG-02-NAT",
    handlingtime: "3",
    mrp: "1999",
    sellingprice: "1999",
    Material: "Acacia Wood",
    Warranty: "12",
    theme: "",
    dimensions: ["33D x 5.1W x 25.4H centimeters"],
    weight: "7",
    keyfeatures: [
      'This beautiful 7-compartments cutlery organizer has 2" deep compartments and can be placed into any drawer or desktop, which helps you to see everything at a glance and keep away from messy. ',
      "Our acacia wood silverware tray for drawer is made of natural acacia with the age of over 4 years, which makes the silverware holder durable enough for long time use. ",
      "The Environmentally material keep our flatware & utensil water and odor resistant. Even the knife won't leave scratch on it. ",
      "Our multi-purpose cutlery organizer is not only suitable for storing silverware, but also suitable for storing disposable tableware, sundries, cosmetics, hair accessories, repair tools, art sets, stationery.",
      "we produce high-quality products that upgrade the quality of life while also providing immaculate customer support. We take the shopping experience of our customers very seriously. ",
    ],
    descriptions: [
      "Our acacia wood drawer organizer is perfect for kitchen storage, for silverware tray&utensil tray &flatware holder&cutlery drawer organizer, knife drawer holder, easily store kitchen gadgets. The flatware organizer for drawer is suitable for home and workplace. Put your usual items in it and you can find it quickly. Moreover, our silverware holder looks orderly, with clear levels, allowing the space to be used rationally. Also, the cutlery organizer looks simple and elegant, and has a wide range of uses.",
    ],
    variants: [
      {
        finish: "Natural",
        images: [
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667396/Altorganizer/products/te3acgvzkr8zmwq9glsh.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667397/Altorganizer/products/hop7uwsqwk9tb5aorsyx.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667397/Altorganizer/products/ekor5ypp86yqrgynoz7j.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667399/Altorganizer/products/c9rinjhutq9yuxcszm4u.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667400/Altorganizer/products/hs0scigktezpvmvwuj4o.jpg",
        ],
      },
    ],
    seotitle:
      "Silverware Organizer Kitchen Drawer Organizer Utensil Organizer Acacia Silverware Holder Cutlery Organizer in Drawer Flatware Organizer Tray(7 slots",
    seodescription:
      "Our acacia wood drawer organizer is perfect for kitchen storage, for silverware tray&utensil tray &flatware holder&cutlery drawer organizer, knife drawer holder, easily store kitchen gadgets. The flatware organizer for drawer is suitable for home and workplace. Put your usual items in it and you can find it quickly. Moreover, our silverware holder looks orderly, with clear levels, allowing the space to be used rationally. Also, the cutlery organizer looks simple and elegant, and has a wide range of uses.",
    seokeywords: "",
    available: true,
    lastupdated: 1738667400567,
  },
  {
    _id: "67a1f601d1bbf1b00c1c842d",
    categories: "Drawer-Organizers",
    rooms: "Kitchen",
    productName: "AltOrganisers Silverware for Kitchen Drawer Organizer",
    sku: "ALT-KITN-ORG-04-NAT",
    handlingtime: "3",
    mrp: "1999",
    sellingprice: "1999",
    Material: "Acacia Wood",
    Warranty: "12",
    theme: "",
    dimensions: ["35.1D x 25.1W x 5.1H centimeters"],
    weight: "7",
    keyfeatures: [
      'This beautiful 7-compartments cutlery organizer has 2" deep compartments and can be placed into any drawer or desktop, which helps you to see everything at a glance and keep away from messy. ',
      "Our acacia wood silverware tray for drawer is made of natural acacia with the age of over 4 years, which makes the silverware holder durable enough for long time use. ",
      "The Environmentally material keep our flatware & utensil water and odor resistant. Even the knife won't leave scratch on it. ",
      "Our multi-purpose cutlery organizer is not only suitable for storing silverware, but also suitable for storing disposable tableware, sundries, cosmetics, hair accessories, repair tools, art sets, stationery.",
      "we produce high-quality products that upgrade the quality of life while also providing immaculate customer support. We take the shopping experience of our customers very seriously. ",
    ],
    descriptions: [
      "Our acacia wood drawer organizer is perfect for kitchen storage, for silverware tray&utensil tray &flatware holder&cutlery drawer organizer, knife drawer holder, easily store kitchen gadgets. The flatware organizer for drawer is suitable for home and workplace. Put your usual items in it and you can find it quickly. Moreover, our silverware holder looks orderly, with clear levels, allowing the space to be used rationally. Also, the cutlery organizer looks simple and elegant, and has a wide range of uses.",
    ],
    variants: [
      {
        finish: "Natural",
        images: [
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667518/Altorganizer/products/wjjke8tfalax8jfq1blg.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667519/Altorganizer/products/loslkbfcyxsz3hzdebzp.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667519/Altorganizer/products/ajr0ybidysethvjgbid0.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667520/Altorganizer/products/vyyov6hosoth3satlsim.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667520/Altorganizer/products/zc8dfhosd8caxc1m5kra.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738667521/Altorganizer/products/dwwii127i2opwetmhtwc.jpg",
        ],
      },
    ],
    seotitle:
      "Silverware Organizer Kitchen Drawer Organizer Utensil Organizer Acacia Silverware Holder Cutlery Organizer in Drawer Flatware Organizer Tray(5 slots)",
    seodescription:
      "Our acacia wood drawer organizer is perfect for kitchen storage, for silverware tray&utensil tray &flatware holder&cutlery drawer organizer, knife drawer holder, easily store kitchen gadgets. The flatware organizer for drawer is suitable for home and workplace. Put your usual items in it and you can find it quickly. Moreover, our silverware holder looks orderly, with clear levels, allowing the space to be used rationally. Also, the cutlery organizer looks simple and elegant, and has a wide range of uses.",
    seokeywords: "",
    available: true,
    lastupdated: 1738667521578,
  },
  {
    _id: "67a1fb26326a2c0bccf9b8c7",
    categories: "Pantry-Organizers",
    rooms: "Kitchen",
    productName:
      "AltOrganisers Foldable Storage Spice Rack Organizer For Kitchen",
    sku: "ALT-KITN-ORG-06-NAT",
    handlingtime: "3",
    mrp: "2999",
    sellingprice: "2999",
    Material: "Acacia Wood",
    Warranty: "12",
    theme: "",
    dimensions: ["20D x 10W x 10H centimeters"],
    weight: "7",
    keyfeatures: [
      "This countertop spice rack and organizer requires no assembly. The 3-tier wooden spice racks free standing helps you to neatly organize the spice jars that take up a lot of room in your drawers, cupboards, and cabinets. It also enables you to display your spice collections elegantly on the countertop and allows you to use the kitchen space more efficiently.",
      "This seasoning organizer measures 9.8*3.15*13 inches. It can store 5-6 spice jars per level. It can also be used in your bathroom holding facial products or other bottles. ",
      "Our free-standing spice rack organizer can be used both laid down and in an upright position. ",
      "The wooden display spice rack organizer is made of natural eco-friendly material that has been cultivated under years of experience to guarantee a long service life. ",
      "It also has a smooth finish to keep you and your child safe and away from getting splinters.",
    ],
    descriptions: [
      "The 3-tier wooden spice racks free standing helps you to neatly organize the spice jars that take up a lot of room in your drawers, cupboards, and cabinets. It also enables you to display your spice collections elegantly on the countertop and allows you to use the kitchen space more efficiently.",
    ],
    variants: [
      {
        finish: "Natural",
        images: [
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738668834/Altorganizer/products/u8yx1pzfemdzqi6mch3e.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738668834/Altorganizer/products/oxeswdukur2kely8irf1.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738668834/Altorganizer/products/oeeqscgtwv2zqzjqwuit.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738668835/Altorganizer/products/tvbif0g2lcw9n1lacsaq.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738668836/Altorganizer/products/henprblknkjfoqxcv6eq.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738668836/Altorganizer/products/knq34oay1en3391hrc34.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738668837/Altorganizer/products/qxkyylfzqf6njjbdhmqp.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738668837/Altorganizer/products/g55lgtjhlsn0nf5lenc9.jpg",
        ],
      },
    ],
    seotitle:
      "Spice Rack Organizer For Kitchen, Sturdy Wood Shelf Seasoning Rack, 3 Tier Free Standing Seasoning Spice Jar Organizer, Foldable Storage Standing for Cabinet, Drawers and Countertop",
    seodescription:
      "The wooden display spice rack organizer is made of natural eco-friendly bamboo material that has been cultivated under years of experience to guarantee a long service life. It also has a smooth finish to keep you and your child safe and away from",
    seokeywords: "",
    available: true,
    lastupdated: 1738668838167,
  },
  {
    _id: "67a3399c45aec56128228284",
    categories: "Pantry-Organizers",
    rooms: "Kitchen",
    productName:
      "AltOrganisers Spice Racks Organizer for Cabinet Storage Shelf - 4 Tier ",
    sku: "ALT-KITN-ORG-06-NAT",
    handlingtime: "3",
    mrp: "2999",
    sellingprice: "2999",
    Material: "Acacia Wood",
    Warranty: "12",
    theme: "",
    dimensions: ["48.3D x 66W x 8.9H centimeters"],
    weight: "7",
    keyfeatures: [
      "Large Capacity: Full 13'' to fit even the widest drawer, large capacity up to 32pcs 4oz jars(jars not included), the separate design is for the use of more drawer sizes, not expandable. ",
      "Efficient Space Saver: Maximize your drawer space by storing your spices horizontally, allowing you to easily see and access each jar. The tiered design ensures that all labels are visible at a glance, ",
      "Easy to Clean: The smooth wood surface is easy to wipe down, keeping your organizer clean and looking great with minimal effort.",
      "Elegant Acacia Wood: Crafted from high-quality Acacia wood, this tray features a rich, natural pattern that adds a touch of sophistication to your space. Its durable construction ensures long-lasting use. ",
      "Utilize Kitchen Drawer: Our spice rack tray can help you to organize the spice bottles in the kitchen drawer. Maximize the available space in the kitchen. ",
    ],
    descriptions: [
      "Our spice rack tray can help you to organize the spice bottles in the kitchen drawer. Maximize the available space in the kitchen. It can turn your kitchen drawer into a large-capacity spice bottle organizer, freeing up more space for your cabinet.",
    ],
    variants: [
      {
        finish: "Honey Oak",
        images: [
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738752246/Altorganizer/products/hwku22isxmhulaho3snw.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738752247/Altorganizer/products/u5vogrdfkepm16c1lfw4.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738752248/Altorganizer/products/hkslzobcjoibs6q2t7wc.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738752248/Altorganizer/products/b61zk8acjeu9wtqzxpel.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738752249/Altorganizer/products/iwrt5fwk89bkglmc3xnf.jpg",
        ],
      },
    ],
    seotitle:
      "Spice Rack Organizer For Kitchen, Sturdy Wood Shelf Seasoning Rack, 3 Tier Free Standing Seasoning Spice Jar Organizer, Foldable Storage Standing for Cabinet, Drawers and Countertop",
    seodescription:
      "The wooden display spice rack organizer is made of natural eco-friendly bamboo material that has been cultivated under years of experience to guarantee a long service life. It also has a smooth finish to keep you and your child safe and away from",
    seokeywords: "",
    available: true,
    lastupdated: 1738752249754,
  },
  {
    _id: "67a3452a6848157c3bed68e2",
    categories: "Pantry-Organizers",
    rooms: "Kitchen",
    productName:
      "AltOrganisers Adjustable Kitchen Utensil Drawer Organizer| Expandable Flatware Caddy",
    sku: "ALT-KITN-ORG-07-NAT",
    handlingtime: "3",
    mrp: "2999",
    sellingprice: "2999",
    Material: "Acacia Wood",
    Warranty: "12",
    theme: "",
    dimensions: ["43.18 x 53.34 x 5.08 cm"],
    weight: "7",
    keyfeatures: [
      'Check Your Drawer Dimensions: This product is suitable for drawers with an inner size larger than 18"D x 22"W and a height greater than 2.5"',
      'Adjustable Size: Utensil and cutlery drawer organizer is expandable from 6 to 8 compartments, goes from 17"D x (12.5" to 21")W x 2"H, provide you the extra space if you need it for your knives, cutlery, and other silverware. Maximize your available storage space in drawers',
      "Multi-Purpose Silverware Drawer Organizer: The expandable acacia kitchen cutlery drawer organizer easily stores flatware, cooking utensils, silverware and other kitchen gadgets. ",
      "Easy To Care: Acacia wood cutlery drawer organizer tray is easy to clean that wipes down easily with a damp cloth you can keep your silverware kitchen drawer organizer looking good for a long time and being an excellent kitchen companion for a long term",
      "Wood Material: The acacia silverware drawer organizer is made of acacia wood, has the advantages of durable, you can upgrade drawers for your home. ",
    ],
    descriptions: [
      "Keep all your kitchen utensils and silverware in order Expandable acacia cutlery organizer with adjustable sides; 6-8 compartments of various sizes; Easy to clean and maintain; This flatware drawer organizer is created with larger and deeper compartments to store all your flatware within reach. Easy to clean and maintain Taking care of your kitchen drawer organizer takes only 5 minutes of your time - just wipe it off with a damp cloth.",
    ],
    variants: [
      {
        finish: "Honey Oak",
        images: [
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738753318/Altorganizer/products/cxy2aenmb1yskfc7eb2u.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738753318/Altorganizer/products/kzizxd4enhhqmwfcmles.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738753319/Altorganizer/products/hk5ulcab2i9p5asaauyr.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738753320/Altorganizer/products/pq9fknevczo5pnnv1a41.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738753320/Altorganizer/products/kw9dawqdresuwwjusg2b.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738753321/Altorganizer/products/dfnqtvwvrplheskoibma.jpg",
          "https://res.cloudinary.com/darxwlgeg/image/upload/v1738753322/Altorganizer/products/hixqve65v8tid1gao6hk.jpg",
        ],
      },
    ],
    seotitle:
      "Silverware Drawer Organizer for Cutlery, Adjustable Kitchen Utensil Drawers Organizers, Expandable Wooden Flatware Caddy, Dividers for Knives, Forks, Spoons, 6-8 Slots",
    seodescription:
      "Multi-Purpose Silverware Drawer Organizer: The expandable acacia kitchen cutlery drawer organizer easily stores flatware, cooking utensils, silverware and other kitchen gadgets. Organizer all your components in order to make feel settled all the time",
    seokeywords: "",
    available: true,
    lastupdated: 1738753322799,
  },
];
