import Navbar from "@/app/_globalcomps/Navbar";
import Searchbarsection from "@/app/_globalcomps/_navbarcomps/Searchbarsection";
import { cookies } from "next/headers";
import Footer from "../_globalcomps/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const allcookes = await cookies();
  const token = allcookes.get("token");

  return (
    <>
      <Navbar navtype={false} token={token} />
      <Searchbarsection />
      {children}
      <Footer />
    </>
  );
}
