import Navbar from "@/app/_globalcomps/Navbar";
import Searchbarsection from "@/app/_globalcomps/_navbarcomps/Searchbarsection";
import Footer from "@/app/_globalcomps/Footer";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const allcookies = await cookies();
  const token = allcookies.get("token");
  const parseduserdata = allcookies.get("userdata")?.value;
  const userdata = parseduserdata ? JSON.parse(parseduserdata) : {};

  return (
    <div>
      <Navbar navtype={true} token={token} userdata={userdata} />
      <Searchbarsection />
      {children}
      <Footer />
    </div>
  );
}
