import Navbar from "@/app/_globalcomps/Navbar";
import Searchbarsection from "@/app/_globalcomps/_navbarcomps/Searchbarsection";
import Footer from "@/app/_globalcomps/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <div>
      <Navbar navtype={true} />
      <Searchbarsection />
      {children}
      <Footer />
    </div>
  );
}
